main: thiestoril.helloworld.HelloWorld
version: 0.0.2
name: HelloWorld

commands:
  github:
    description: Sens my GitHub account to the player.
  helloworld:
    description: Main command of the plugin.